### ISSUE TITLE
without SQL analysis

### ISSUE THREAD

**Issue by BlingArida** [arosenfeld/immunedb#78]
Dear，
I was wondering wheather the immunedb does analysis of Rep-seq on one local machine. Because of permission denied ,I can't install SQL database. And I can't install docker.
Is there anyway I can do analysis just use the python package immundb.

Thank you very much!

Best Regards,
Bling Arida

**Comment by arosenfeld** [comment]
ImmuneDB does run on one machine, but it requires MySQL.  You can attempt to install MySQL as a normal user with something like this (note I've not actually tried this):

https://dzone.com/articles/setting-up-mysql-without-root-access

Alternatively, you can run a MySQL server on another machine where you do have root permissions and specify the database host when using `immunedb_admin create` with the `--db-host` flag.
