### ISSUE TITLE
Error in docs - I think...

### ISSUE THREAD

**Issue by bcorrie** [arosenfeld/immunedb#81]
Hi Aaron,

I recently downloaded and installed the ImmuneDB docker container. 

I notice that on the following page in your documentation that I think you have a copy paste error 8-)

https://github.com/arosenfeld/immunedb/blob/master/docs/pipeline_full.rst

For Human T-cell you list imgt_mouse_traj and imgt_mouse_trbj. Those files don't exist in the docker container so I am pretty sure its an error in the docs...

imgt_human_ighv & imgt_human_ighj: Human B-cell heavy chains
imgt_human_trav & imgt_mouse_traj: Human T-cell α chains
imgt_human_trbv & imgt_mouse_trbj: Human T-cell β chains
imgt_mouse_ighv & imgt_mouse_ighj: Mouse B-cell heavy chains

Brian

**Comment by arosenfeld** [comment]
Hi Brian,

You are indeed correct.  This has been fixed in develop and will go out with the next release.

Thanks!
