### ISSUE TITLE
use of  compressed fastq 

### ISSUE THREAD

**Issue by aurelBZH** [arosenfeld/immunedb#89]
Hello, 
thanks for the work on immune_db. I was trying immune_db an i'm wondering why immune_db can't use compressed fastq, immune_db don't detect fastq.gz. It's a bit annoying to have to store fastq file as uncompressed fastq. I think that decompressing files on the fly would not be a difficult change and would be very convenient.

thanks a lot 
Aurélien Béliard 
Bioinformatician 
I3 lab

**Comment by arosenfeld** [comment]
I've added support for `.gz` files to `immunedb_identify` and made a release v0.29.6.

Let me know if this addresses your needs.

**Comment by aurelBZH** [comment]
thanks a lot for your fast answer. i'll try
