### ISSUE TITLE
problem with vj identification 

### ISSUE THREAD

**Issue by aurelBZH** [arosenfeld/immunedb#90]
Hi 
thanks for the modification compressed fastq it seem to work perfectly but i have another problem.
The identification step seem to don't work at all.

immunedb_identify /share/configs/my_db.json       /root/germlines/imgt_human_trbv.fasta       /root/germlines/imgt_human_trbj.fasta   /RepSeq/RS_Data/iReceptor/Data_loaded/test_data/

this command for identification of beta v and j gene return an error  like this one for every read :
Unexpected error processing sequence SN7001332:407:HY7MMBCX2:1:2216:18616:100831 1:N:0:TCCGCGAA+GGCTCTGA max() arg is an empty sequence
At the end there isn't any v j gene for clonality assessement.

while the same fastq file is processed without any problem by mixcr. 
Could you help with this problem?
thanks a lot 
Aurélien béliard
i3lab
Sorbonne université

**Comment by aurelBZH** [comment]
here is few sequence from one of the files that aren't working.
@SN7001332:407:HY7MMBCX2:1:1106:1279:1980 1:N:0:CGGCTATG+CCTATCCN
CGCCTGATCTCTCAGCTGGTACACGGCAGGGTCAGGGTTCTGGATATCAGGCCGGACCAGCAGTCTGGTCCCACTCCCGAAGATCAATTTATAGCTGCTATCCATCCCACAGTGTTTCTTAGTCAGTCAAAAACACCCAGAAGCCCACACATCCTTTTCATACCTAAGACCTAGAGATATCCCCGTACTCTGCGTTGATACCACTGCTTGATCGTG
+
DDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIIIIIIIIHIIIIIIIIIHIIIIIIIIIIIIIIIHIIHIIGIIIIIIIIIIIIIIIFHIIIIIHIIIIIHIIIIIIIIIIIHIIIIIIIIIIIHHIHIHHIIIIIIIIIIIHEIIIHHHIHIH@@HHIIEHEG@GHIIIHIGIIGHHIIIIHIIIIIGIIIEHHECHHIII
@SN7001332:407:HY7MMBCX2:1:1106:1824:1991 1:N:0:CGGCTATG+CCTATCCN
TCGTTTGAGATCTCTGCTCTGATGGCTCAAACACAGCGACCTCGGGTGGGAACACGTTTTTCAGGTCCTCGAGCACTGTCAGCCGGGTGCCTGGGCCAAAATACTGCGTATCTGTGCTCACAGCCTGGAGGCCCAGGACAAAAACCGGTGCTGCCCGCTCTGCTGTCCCAGACTCAGCTCGGGTCCTTCCCACCGCTGAGAGCCCCATCGCTCTCCCAGCACCCAGAACCAGGAGTCCTCCGCCCAGACGCCCAGCAGCGCCTCTCAGCACAGCACCCCCGTACTCTGCGTTGATACCAC
+
DDDDDIHIHIIIIIIIIIIICHI1DGHIGIIIIIGIIIDFEHIHIIHIIIIHCHI0<@GHIHHIIIIHHIC<CHHGHIHHHEHIIDIIIIEH?EHHIIGII<FHEEHIIHIIIIIIIGIIIIIIIHHIHIIIIIHIHGEHEHIEHIIDEHDGHHHHHHDHHHIHHHHHIGCGHFHHHIIIFHH@HHIHHHI.FCCHIC8GHH?EHIHIIHHEH.GHHHCHECHE?E7FHE--AEE8B?@GH@GIH=-@B=<DC-8GH-B>HI-@-B@-@-@H---@GHCD6-7EBG-68,4@CC--@F@6
@SN7001332:407:HY7MMBCX2:1:1106:4559:2000 1:N:0:CGGCTATG+CCTATCCN
TTGCTATAGATCTCTGCTTCTGATGGCTCAAACACAGCGACCTCGGGTGGGAACACGTTTTTCAGGTCCTCCAGTACGGTCAGCCTAGAGCCTTCTCCAAAAAACAGCTCCCCGGCGGCCCCTAGTCCCGGTTTCCTCTCTGGGCTGCTGGCACAGAAATAAACTCCAGAATCCTCCAGTTCTGCAGGCTGCACCTTCAGAGTAGAATACGTCCCTCCAGTCCTTTCAGCTAAGAATCGATTGTTGGGCATACCGGACTCATCCTGTTTAGACTCTTTCACAAAATGTAACAGAAATTTT
+
DDDDDIIIIFHIGIIIIIIIIIIIIIIIIIHIIIIIIGIIIIIIIIIIIIIIHIHHIIIHIIIHGHIIIIIIIIIHIIGIIIIHIIIHGHIIIGIIGIIIIGHHIIIIIIIIIHDHIIHIIIIIIIIGIIGIIIHHIIIIIIGIIIIIIIIGIIIHEHIHHIIIGIHIHGHIIIIIHHEHIHIIIIIHIIIIIHHIIIHIIIIIIIIIIIIHE.GHHHHGAGFH?GHHHIHF-A-BFHH?-BEHHICHGCGHEIIDHIHHHIHIIIIIHHE-G@EHFE@FHGHHCCHGCCHHHCHC@@FH
@SN7001332:407:HY7MMBCX2:1:1106:5850:1991 1:N:0:CGGCTATG+CCTATCCN
TGTGAGTAGATCTCTGCTTCTGATGGCTCAAACACAGCGACCTCGGGTGGGAACACCTTGTTCAGGTCCTCTCCAGGCACTGTCCTCAGGATGTTTTGAGCTCCTTAGAGCTGGATGTCTTTGTAAGGCTGTTTGGCGAAGGGGCTGGTCTTCTCCAGTACCCACCCCTCTCCAAGCTGTTGTCACGTTGGGGCATCCCCGTACTCTGCGTTGATACCACTGCTTAAAGGAT
+
DDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIEHHFCHIHHGCHIIHIGHHHIIHIIIIHIIIIIIIIIIHHHDHIIIIIIIIIHIIIHIIIIIIHHHIIIIHHIIHECHHIIEHHHHIIIIIHHHIHHHIIGHIIHHGHIHGHIHIIIHHGHIHIIIHIHEF?FH
@SN7001332:407:HY7MMBCX2:1:1106:10051:1985 1:N:0:CGGCTATG+CCTATCCN
CAGACATTCTCTCAGCTGGTACACGGCAGGGTCAGGGTTCTGGATATTTGGATTCACGGTTAAGAGAGTTCCTTTTCCAAATGTCAGTTTATAGTTACCCGCACAGGCCAGAAGACAGTAGTACACGGCTGAGTCTGATACCTGGACTGAATATTTCACAATGGGGGAGTTTTTGTCTTTAATATTTCCGCCTCCGAAGTTTTTGCTGTTTTCCATTGTCTCTCTCTGAAGAAGCTGCAGAGGTTTGCTGGGGTATTCCACATACCAGAAAAGGGTAGGGTACCCCGTGGATGTGTATGT
+
DDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIHHIIIHIHHHHIIIIIIIIIIIHIIIHIHIIIIIIIIIIIHIEHIIIIHIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIHIIIIIIIIIIHHHHIIHIIIHHIGIIIIHH<FHFHHHIEEHIGHIIIIIEHIIIIHIHHHHHEHIH?HHHIIIIIIHIFHH@EGHGHHICEHHIIGFHHEHHIHFEFHE?FHHHDHHH--8@@HHIIFF?GHHEFIHHH?GHIHHEHHHFH=-@GH-86-6
@SN7001332:407:HY7MMBCX2:1:1106:10671:1982 1:N:0:CGGCTATG+CCTATCCN
ATGTAATAGATCTCTGCTTCTGATGGCTCAAACACAGCGACCTCGGGTGGGAACACGTTTTTCAGGTCCTCTGTGACCGTGAGCCTGGTGCCCGGCCCGAAGTACTGCTCGTAGGTCTGCCCCAAGCTGCTGGCACAGAGATAGAGGGCCGAGTCCCCCAGCAACAAGGCGTTCACATTCAGCTCAGAGCTATAGTTAGGGAACTGGTGACCTGAGAATCGATCAGGGAAGTTGCCTCTCTGTCTCTCTTCCTCCTCATAATACTGAAAGATAAACTGGGGCCCCTGACCCAGGGCCTGT
+
DDDDDIIIIIIIHIIIIIIHIIIHIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIICHHIIIIIIIIHIIHIIIIIIIIIIIIGHIGHIIIIHHIIIIHIEHIIIIIIIIIIIIFHIIIIIIIIIIIIIIIIIIIIIHHHHIIIGIIHIIHIIIIIHIIIIIIHIIIIGIIIIHHIIIIIIIIIHIIHEHHHHHIIGHHHHCHIHGHHIHIIHIHIEHEHIHHEHHEHIEHIIIIGHIEHHHHHEHHHIIIHFEG@GHHHHIIIGGH-@@EEHGHIHGHHGDHHH-GHHI-FHFHH=H-
@SN7001332:407:HY7MMBCX2:1:1106:11415:1966 1:N:0:CGGCTATG+CCTATCCN
NCCCGCAGATCTCTGCTTCTGATGGCTCAAACACAGCGACCTCGGGTGGGAACACGTTTTTCAGGTCCTCGAGCACTGTCAGCCGGGTGCCTGGGCCAAAATATTGCGTATCTGTGCTCACAGCCTGGAGGCCCAGGACAAAAACCGGTGCTGCCCGCTCTGCTGTCCCAGACTCAGCTCGGGTCCTTCCCACCGCTGAGAGCCCCATCGCTCTCCCAGCACCCAGAACCAGGAGTCCCCCGTACTCTGCGTTGATACCACTGCTTTAATACA
+

**Comment by arosenfeld** [comment]
I'm not entirely sure what's causing that error since the sequences above don't cause it.

That said, you may want to consider using IgBLAST instead of the anchoring method, especially for TCR. If you upgrade to v0.29.8, there is a helper script included so you don't have to do this manually.

https://immunedb.readthedocs.io/en/latest/pipeline_full.html#running-igblast-optional
