### ISSUE TITLE
Retrieving Full BCR sequence

### ISSUE THREAD

**Issue by ajulienla** [arosenfeld/immunedb#91]
Dear Aaron,
I have been trying to assemble mouse hybridomas sequences obtained from SMARTer Mouse BCR IgG H/K/L Profiling (Takara lab),
I was able to run ImmuneDB and obtain intial clone assesment. However, I am wondering on the possible procedure to follow in order to retrieve the initial hybridomas BCR sequences, not only the initial aligned germline one. 
Is this a possibility for ImmuneDB ?

Best,
Alice

**Comment by arosenfeld** [comment]
Hi Alice,

Just to clarify, the aligned query sequence and germline reference are stored for all sequences which you can retrieve with `immunedb_export`.

Are you interested in the portion of the sequence that is 5' of the V or 3' of the J?  Currently that information is not stored in the database, but modifications could be made to retain that data if there is a use case for it.

**Comment by ajulienla** [comment]
Dear Aaron,
Thank you very much for your quick reply.
Indeed, what I needed where the sequences and thus this use case is already implemented in your software.
Thank you very much.
