### ISSUE TITLE
error when running run_igblast.sh

### ISSUE THREAD

**Issue by linquynus** [arosenfeld/immunedb#92]
Hi,

Thanks for the great tool. I had an error as below when running run_igblast.sh. The command line I used is "run_igblast.sh human TRA /share/input/ /share/input/". 

Error: 
_Running IgBLAST on /share/input//filtered_contig.fasta (saving to /share/input//filtered_contig.fasta.airr.tsv)
BLAST Database error: No alias or index file found for nucleotide database [/apps/igblast/database/human/TRAD.edited.fasta] in search path [/share/input::]_

Indeed, there should be only VJ recombination for TRA. However, it seems the script is still trying to look for D genes in TRA.

Best,
Quy

**Comment by arosenfeld** [comment]
Hi Quy,

I believe it's because IgBLAST requires a D-gene germline file even if it's not used.

I'll look into it soon.

Best,
Aaron

**Comment by arosenfeld** [comment]
Hi Quy,

This should be resolved in the develop branch.  I tried a small TRA dataset and IgBLAST worked as expected.  Can you give your data a try and let me know how it goes?

Best,
Aaron
