### ISSUE TITLE
Error when running igblast.sh with IGL and IGK options (human)

### ISSUE THREAD

**Issue by Elyes88** [arosenfeld/immunedb#97]
Hi,
 
Thanks for this tool. It works perfectly with VH sequences, but when I wanted to try it on kappa and lambda locus, I had the following error:
 
BLAST Database error: No alias or index file found for nucleotide database [/apps/igblast/database/human/IGLD.edited.fasta] in search path [/root::]

I think it is the same error as the one reported in the last issue, when user tried to do the analysis on TRA. There is no D region for kappa and lambda
I don't know who to manage this error, would you please help me.

Best regards,
Elyes

**Comment by arosenfeld** [comment]
I've made a fix in the dev branch.  Please give it a try and let me know if it works for you.  If so, I'll merge it into master for the next release.
